<a href="https://colab.research.google.com/github/akankshaagr12/ML-practicals/blob/main/encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [3]:
import zipfile

zip_file_path = "/content/weather.zip"
extract_path = "/content/"

# Extract the contents of the zip file
with zipfile.ZipFile(zip_file_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

# Assuming the CSV is directly inside the extracted folder from the error message
# '515849391ad37fe593997fe0db98afaa-f663366d17b7d05de61a145bbce7b2b961b3b07f/weather.csv'
csv_file_path = extract_path + "515849391ad37fe593997fe0db98afaa-f663366d17b7d05de61a145bbce7b2b961b3b07f/weather.csv"

df = pd.read_csv(csv_file_path)
df.head()

    outlook temperature humidity  windy play
0  overcast         hot     high  False  yes
1  overcast        cool   normal   True  yes
2  overcast        mild     high   True  yes
3  overcast         hot   normal  False  yes
4     rainy        mild     high  False  yes

In [4]:
df.info()
df.describe(include='all')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   outlook      14 non-null     object
 1   temperature  14 non-null     object
 2   humidity     14 non-null     object
 3   windy        14 non-null     bool
 4   play         14 non-null     object
dtypes: bool(1), object(4)
memory usage: 594.0+ bytes

       outlook temperature humidity  windy play
count       14          14       14     14   14
unique       3           3        2      2    2
top      rainy        mild     high  False  yes
freq         5           6        7      8    9

In [5]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

for col in df.select_dtypes(include='object').columns:
    df[col] = le.fit_transform(df[col])

df.head()

   outlook  temperature  humidity  windy  play
0        0            1         0  False     1
1        0            0         1   True     1
2        0            2         0   True     1
3        0            1         1  False     1
4        1            2         0  False     1

In [6]:
df_encoded = pd.get_dummies(df, drop_first=True)

df_encoded.head()

   outlook  temperature  humidity  windy  play
0        0            1         0  False     1
1        0            0         1   True     1
2        0            2         0   True     1
3        0            1         1  False     1
4        1            2         0  False     1

In [8]:
X = df_encoded.drop("play", axis=1)
y = df_encoded["play"]

In [9]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)